name: 'DokuWiki Environment creator'
description: 'Install DokuWiki environment for plugin testing'
inputs:
  branch:
    description: 'The DokuWiki branch to test against'
    required: true
    default: 'master'
outputs:
  type:
    description: 'The type of extension this is (plugin or template)'
  base:
    description: 'The base name of the extension'
  dir:
    description: 'The full directory name of the extension (lib/plugins/<base> or lib/tpl/<base>)'
  minphp:
    description: 'The minimum PHP version required by the extension, if set. Otherwise empty.'
  maxphp:
    description: 'The maximum PHP version compatible with the extension, if set. Otherwise empty.'
runs:
  using: 'node20'
  main: 'index.js'
