name: PHP Code Style

on: [ workflow_call ]

permissions:
  contents: read
  pull-requests: read

jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    env:
      COMPOSER: _test/composer.json
      COMPOSER_VENDOR_DIR: _test/vendor

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, PDO, pdo_sqlite, bz2

      - name: Create DokuWiki Environment
        id: dokuwiki-env
        uses: dokuwiki/github-action/.github/actions/dokuenv@prv6
        with:
          branch: master

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader --no-scripts

      - name: Run PHP codesniffer
        run: composer exec -- phpcs -q --standard=_test/phpcs.xml ${{ steps.dokuwiki-env.outputs.dir }}
